name: mvl_desafio
description: "MVL Desafio"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  dart_frog: ^1.1.0
  desafio_shared:
    git:
      url: https://github.com/ModelViewLabsOrg/desafio_shared.git
  uuid: ^4.5.1
  intl: ^0.19.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.25.5

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
